#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps OpenAPI
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId 'cdbb4478-e23e-4bfa-8f7a-1adde1799aca'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['ApiEndpoint'] = Read-GitHubInput -Name 'api_endpoint'
$P['Authentication'] = Read-GitHubInput -Name 'authentication'
$P['AzureTenantId'] = Read-GitHubInput -Name 'azure_tenant_id'
$P['AzureAppClientId'] = Read-GitHubInput -Name 'azure_app_client_id'
$P['AzureAppClientCertificate'] = Read-GitHubInput -Name 'azure_app_client_certificate'
$P['Username'] = Read-GitHubInput -Name 'username'
$P['FixedTag'] = Read-GitHubInput -Name 'fixed_tag'
$P['ApiRoutes'] = Read-GitHubInput -Name 'api_routes'
$P['ApiExcludeRoutes'] = Read-GitHubInput -Name 'api_exclude_routes'
$P['ApiServers'] = Read-GitHubInput -Name 'api_servers'

$P['Usedocker'] = Read-GitHubInput -Name 'usedocker' -AsBool
$P['Discover'] = Read-GitHubInput -Name 'discover' -AsBool
$P['InspectPaths'] = Read-GitHubInput -Name 'inspect_paths' -AsBool
$P['ExportEdmx'] = Read-GitHubInput -Name 'export_edmx' -AsBool
$P['ExportYaml'] = Read-GitHubInput -Name 'export_yaml' -AsBool
$P['ExportJson'] = Read-GitHubInput -Name 'export_json' -AsBool
$P['ExcludeCompanyPaths'] = Read-GitHubInput -Name 'exclude_company_paths' -AsBool
$P['PublishArtifacts'] = $true

$P['AzureAppClientSecret'] = Read-GitHubInput -Name 'azure_app_client_secret'
if ($P['AzureAppClientSecret']) { Protect-ALOpsSecret $P['AzureAppClientSecret'] }
$P['AzureAppClientCertificatePassword'] = Read-GitHubInput -Name 'azure_app_client_certificate_password'
if ($P['AzureAppClientCertificatePassword']) { Protect-ALOpsSecret $P['AzureAppClientCertificatePassword'] }
$P['Password'] = Read-GitHubInput -Name 'password'
if ($P['Password']) { Protect-ALOpsSecret $P['Password'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsOpenAPIV3Step @P

    # Safety net: a step that logged errors but returned without throwing must
    # not be reported green (issue #996). A step that deliberately tolerates
    # errors opts out by declaring its own result via Set-ALOpsResult.
    $taskStatus = Get-ALOpsTaskStatus
    if ($taskStatus.ErrorCount -gt 0 -and -not $taskStatus.ResultDeclared) {
        $netMsg = "ALOps OpenAPI logged $($taskStatus.ErrorCount) error(s). First: $($taskStatus.FirstError)"
        Set-ALOpsResult -Result "Failed" -Message $netMsg
        exit 1
    }

    # Warnings turn the step orange (issue #1000): logged warnings with no
    # declared result -> SucceededWithIssues. A step that deliberately
    # tolerates warnings opts out by declaring its own result.
    if (-not $taskStatus.ResultDeclared -and $taskStatus.WarningCount -gt 0 -and $env:ALOPS_DISABLE_WARNING_RESULT -ne 'true') {
        Set-ALOpsResult -Result "SucceededWithIssues" -Message "ALOps OpenAPI completed with $($taskStatus.WarningCount) warning(s). First: $($taskStatus.FirstWarning)"
    } elseif (-not $taskStatus.ResultDeclared) {
        Set-ALOpsResult -Result "Succeeded" -Message "ALOps OpenAPI completed successfully."
    }
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
