name: $(Build.BuildId)

variables:
  - group: Secrets

pool: HOD-DOCKER

trigger: none

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    appversiontemplate: '1.0.*.0'
    publishartifact: false
    alternativevsixurl: '6.5.413786' # possibilities are a localpath, a url (preferred), or a version for downloading it from the marketplace.  
    #alternativevsixurl: 'Latest'    # You can also use "Latest" to get the latest from the marketplace (important for using custom codecops)
    #alternativevsixurl: 'Prerelease' # to use the Prerelease version of the VSIX