#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps App Publish
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId 'c004e2d2-e842-40f0-9ed4-89fb9bdd2e33'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['NavServerinstance'] = Read-GitHubInput -Name 'nav_serverinstance'
$P['PublishScope'] = Read-GitHubInput -Name 'publish_scope'
$P['Tenant'] = Read-GitHubInput -Name 'tenant'
$P['ArtifactPath'] = Read-GitHubInput -Name 'artifact_path'
$P['NavArtifactAppFilter'] = Read-GitHubInput -Name 'nav_artifact_app_filter'
$P['BatchPublishFolder'] = Read-GitHubInput -Name 'batch_publish_folder'
$P['FixedTag'] = Read-GitHubInput -Name 'fixed_tag'
$P['InstallAlAppNames'] = Read-GitHubInput -Name 'install_al_app_names'
$P['PublisherAzureAdTenantId'] = Read-GitHubInput -Name 'publisher_azure_ad_tenant_id'

$P['InstallPublishedApps'] = Read-GitHubInput -Name 'install_published_apps' -AsBool
$P['SkipVerification'] = Read-GitHubInput -Name 'skip_verification' -AsBool
$P['ForceInstall'] = Read-GitHubInput -Name 'force_install' -AsBool
$P['ForceSync'] = Read-GitHubInput -Name 'force_sync' -AsBool
$P['BlockSymbolsOnly'] = Read-GitHubInput -Name 'block_symbols_only' -AsBool
$P['ExcludeMicrosoftApps'] = Read-GitHubInput -Name 'exclude_microsoft_apps' -AsBool
$P['Usedocker'] = Read-GitHubInput -Name 'usedocker' -AsBool
$P['InstallAlTestTool'] = Read-GitHubInput -Name 'install_al_test_tool' -AsBool
$P['StrictAppNames'] = Read-GitHubInput -Name 'strict_app_names' -AsBool



# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAppPublishV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps App Publish completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
