#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps App Sign
#
# This wrapper does exactly three things:
#   1. Import the module (installing the pinned or newest PSGallery version
#      only when it is not present yet) and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────
# Module version pin. tools/Update-ALOpsVSIX.ps1 -ModuleVersion stamps the full
# PSGallery tag (e.g. 0.1.11557-alpha) here for the Azure DevOps extension.
# Empty = resolve the newest prerelease on PSGallery every run (GitHub Actions,
# local builds). Setting the alops_module_latest environment variable to any
# non-empty value (name matched case-insensitively) forces that even when pinned.
$ALOpsModuleVersion = ''

function Import-ALOpsWrapperModule {
    param([string] $RequiredVersion, [int] $RetryCount = 3, [int] $RetryDelaySeconds = 15)

    $moduleName = 'ALOpsV3.Module'
    $latestFlag = [bool](Get-ChildItem -Path Env: | Where-Object {
        $_.Name -ieq 'alops_module_latest' -and -not [string]::IsNullOrWhiteSpace($_.Value)
    })

    if ([string]::IsNullOrWhiteSpace($RequiredVersion) -or $latestFlag) {
        try {
            $RequiredVersion = [string](Find-Module -Name $moduleName -Repository PSGallery -AllowPrerelease -ErrorAction Stop).Version
            Write-Host "ALOpsV3.Module mode: latest (PSGallery -> $RequiredVersion)"
        } catch {
            Write-Host "PSGallery lookup failed ($($_.Exception.Message)); importing the newest installed $moduleName."
            Import-Module -Name $moduleName -Force -DisableNameChecking -ErrorAction Stop
            return
        }
    } else {
        Write-Host "ALOpsV3.Module mode: pinned ($RequiredVersion)"
    }

    # PSGallery needs the full '1.2.3-tag' string; the on-disk folder and
    # Get-Module/Import-Module use the numeric part only.
    $baseVersion = ($RequiredVersion -split '-', 2)[0]
    $spec = @{ ModuleName = $moduleName; RequiredVersion = $baseVersion }

    if (-not (Get-Module -ListAvailable -FullyQualifiedName $spec)) {
        # Serialize installs per machine/account: parallel agents under one
        # profile raced on the same module folder (issue #997).
        $mutex = $null; $acquired = $false
        try {
            $mutex = [System.Threading.Mutex]::new($false, 'Global\ALOpsV3.Module.Install')
            try { $acquired = $mutex.WaitOne([TimeSpan]::FromMinutes(10)) }
            catch [System.Threading.AbandonedMutexException] { $acquired = $true }
            if (-not $acquired) { Write-Host 'Install lock wait timed out; continuing without lock.' }
        } catch { Write-Host "Install lock unavailable: $($_.Exception.Message)" }
        try {
            if (-not (Get-Module -ListAvailable -FullyQualifiedName $spec)) {
                for ($attempt = 1; $attempt -le $RetryCount; $attempt++) {
                    try {
                        Write-Host "Installing $moduleName $RequiredVersion (attempt $attempt of $RetryCount)..."
                        Install-Module -Name $moduleName -RequiredVersion $RequiredVersion -AllowPrerelease -Scope CurrentUser -AllowClobber -Force -ErrorAction Stop
                        break
                    } catch {
                        if ($attempt -ge $RetryCount) { throw }
                        Write-Host "Install failed: $($_.Exception.Message). Retrying in $RetryDelaySeconds s..."
                        Start-Sleep -Seconds $RetryDelaySeconds
                    }
                }
            }
        } finally {
            if ($acquired) { $mutex.ReleaseMutex() }
            if ($mutex) { $mutex.Dispose() }
        }
    }

    Import-Module -FullyQualifiedName $spec -Force -DisableNameChecking -ErrorAction Stop
}

Import-ALOpsWrapperModule -RequiredVersion $ALOpsModuleVersion

Initialize-ALOpsTask -TaskId '9f152d4d-9616-47f8-a0a8-fc1a8c88afbe'

$ALOpsLoadedModule = Get-Module -Name ALOpsV3.Module
Write-ALOpsInfo "ALOpsV3.Module version: $($ALOpsLoadedModule.Version)-$($ALOpsLoadedModule.PrivateData.PSData.Prerelease) (pin: '$ALOpsModuleVersion')"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['Signmethod'] = Read-GitHubInput -Name 'signmethod'
$P['FixedTag'] = Read-GitHubInput -Name 'fixed_tag'
$P['TimestampUri'] = Read-GitHubInput -Name 'timestamp_uri'
$P['Hsmmethod'] = Read-GitHubInput -Name 'hsmmethod'
$P['HsmDescription'] = Read-GitHubInput -Name 'hsm_description'
$P['HsmDescriptionUrl'] = Read-GitHubInput -Name 'hsm_description_url'
$P['HsmDigestalgorithm'] = Read-GitHubInput -Name 'hsm_digestalgorithm'
$P['ArtifactPath'] = Read-GitHubInput -Name 'artifact_path'
$P['NavArtifactAppFilter'] = Read-GitHubInput -Name 'nav_artifact_app_filter'
$P['PfxPath'] = Read-GitHubInput -Name 'pfx_path'
$P['HsmSigningEndpoint'] = Read-GitHubInput -Name 'hsm_signing_endpoint'
$P['HsmSigningAccount'] = Read-GitHubInput -Name 'hsm_signing_account'
$P['HsmTrustedCertificateprofile'] = Read-GitHubInput -Name 'hsm_trusted_certificateprofile'
$P['HsmKeyvaultName'] = Read-GitHubInput -Name 'hsm_keyvault_name'
$P['HsmKeyvaultCertificateName'] = Read-GitHubInput -Name 'hsm_keyvault_certificate_name'
$P['HsmTenantid'] = Read-GitHubInput -Name 'hsm_tenantid'
$P['HsmClientid'] = Read-GitHubInput -Name 'hsm_clientid'

$P['Usedocker'] = Read-GitHubInput -Name 'usedocker' -AsBool
$P['Batchsigncompiledapps'] = Read-GitHubInput -Name 'batchsigncompiledapps' -AsBool
$P['PublishArtifact'] = $true

$P['PfxPassword'] = Read-GitHubInput -Name 'pfx_password'
if ($P['PfxPassword']) { Protect-ALOpsSecret $P['PfxPassword'] }
$P['HsmClientSecret'] = Read-GitHubInput -Name 'hsm_client_secret'
if ($P['HsmClientSecret']) { Protect-ALOpsSecret $P['HsmClientSecret'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAppSignV3Step @P

    # Safety net: a step that logged errors but returned without throwing must
    # not be reported green (issue #996). A step that deliberately tolerates
    # errors opts out by declaring its own result via Set-ALOpsResult.
    $taskStatus = Get-ALOpsTaskStatus
    if ($taskStatus.ErrorCount -gt 0 -and -not $taskStatus.ResultDeclared) {
        $netMsg = "ALOps App Sign logged $($taskStatus.ErrorCount) error(s). First: $($taskStatus.FirstError)"
        Set-ALOpsResult -Result "Failed" -Message $netMsg
        exit 1
    }

    # Warnings turn the step orange (issue #1000): logged warnings with no
    # declared result -> SucceededWithIssues. A step that deliberately
    # tolerates warnings opts out by declaring its own result.
    if (-not $taskStatus.ResultDeclared -and $taskStatus.WarningCount -gt 0 -and $env:ALOPS_DISABLE_WARNING_RESULT -ne 'true') {
        Set-ALOpsResult -Result "SucceededWithIssues" -Message "ALOps App Sign completed with $($taskStatus.WarningCount) warning(s). First: $($taskStatus.FirstWarning)"
    } elseif (-not $taskStatus.ResultDeclared) {
        Set-ALOpsResult -Result "Succeeded" -Message "ALOps App Sign completed successfully."
    }
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
