#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps App Sign
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId '9f152d4d-9616-47f8-a0a8-fc1a8c88afbe'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['Signmethod'] = Read-GitHubInput -Name 'signmethod'
$P['FixedTag'] = Read-GitHubInput -Name 'fixed_tag'
$P['TimestampUri'] = Read-GitHubInput -Name 'timestamp_uri'
$P['Hsmmethod'] = Read-GitHubInput -Name 'hsmmethod'
$P['HsmDescription'] = Read-GitHubInput -Name 'hsm_description'
$P['HsmDescriptionUrl'] = Read-GitHubInput -Name 'hsm_description_url'
$P['HsmDigestalgorithm'] = Read-GitHubInput -Name 'hsm_digestalgorithm'
$P['ArtifactPath'] = Read-GitHubInput -Name 'artifact_path'
$P['NavArtifactAppFilter'] = Read-GitHubInput -Name 'nav_artifact_app_filter'
$P['PfxPath'] = Read-GitHubInput -Name 'pfx_path'
$P['HsmSigningEndpoint'] = Read-GitHubInput -Name 'hsm_signing_endpoint'
$P['HsmSigningAccount'] = Read-GitHubInput -Name 'hsm_signing_account'
$P['HsmTrustedCertificateprofile'] = Read-GitHubInput -Name 'hsm_trusted_certificateprofile'
$P['HsmKeyvaultName'] = Read-GitHubInput -Name 'hsm_keyvault_name'
$P['HsmKeyvaultCertificateName'] = Read-GitHubInput -Name 'hsm_keyvault_certificate_name'
$P['HsmTenantid'] = Read-GitHubInput -Name 'hsm_tenantid'
$P['HsmClientid'] = Read-GitHubInput -Name 'hsm_clientid'

$P['Usedocker'] = Read-GitHubInput -Name 'usedocker' -AsBool
$P['Batchsigncompiledapps'] = Read-GitHubInput -Name 'batchsigncompiledapps' -AsBool
$P['PublishArtifact'] = $true

$P['PfxPassword'] = Read-GitHubInput -Name 'pfx_password'
if ($P['PfxPassword']) { Protect-ALOpsSecret $P['PfxPassword'] }
$P['HsmClientSecret'] = Read-GitHubInput -Name 'hsm_client_secret'
if ($P['HsmClientSecret']) { Protect-ALOpsSecret $P['HsmClientSecret'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAppSignV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps App Sign completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
