#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps App License Check
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId 'c5941156-348d-4a9d-8c35-a463b8ffab40'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['Licensefile'] = Read-GitHubInput -Name 'licensefile'
$P['ExpiryText'] = Read-GitHubInput -Name 'expiry_text'
$P['ExpiryDateformat'] = Read-GitHubInput -Name 'expiry_dateformat'
$P['ExpiryDayswarning'] = Read-GitHubInput -Name 'expiry_dayswarning'
$P['ArtifactPath'] = Read-GitHubInput -Name 'artifact_path'
$P['ArtifactFilter'] = Read-GitHubInput -Name 'artifact_filter'
$P['ArtifactInclude'] = Read-GitHubInput -Name 'artifact_include'
$P['ArtifactExclude'] = Read-GitHubInput -Name 'artifact_exclude'
$P['ExcludeRanges'] = Read-GitHubInput -Name 'exclude_ranges'
$P['AltoolPackageVersion'] = Read-GitHubInput -Name 'altool_package_version'

$P['ExpiryCheckonly'] = Read-GitHubInput -Name 'expiry_checkonly' -AsBool
$P['UseAlopsCompilerApps'] = Read-GitHubInput -Name 'use_alops_compiler_apps' -AsBool
$P['ExcludeTables'] = Read-GitHubInput -Name 'exclude_tables' -AsBool
$P['ExcludeCodeunits'] = Read-GitHubInput -Name 'exclude_codeunits' -AsBool
$P['ExcludePages'] = Read-GitHubInput -Name 'exclude_pages' -AsBool
$P['ExcludeReports'] = Read-GitHubInput -Name 'exclude_reports' -AsBool
$P['ExcludeXmlports'] = Read-GitHubInput -Name 'exclude_xmlports' -AsBool
$P['ExcludeQueries'] = Read-GitHubInput -Name 'exclude_queries' -AsBool
$P['WarningOnly'] = Read-GitHubInput -Name 'warning_only' -AsBool



# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAppLicenseCheckV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps App License Check completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
