name: $(Build.BuildId)

pool: HOD-DOCKER

trigger: none

variables:
- group: 'Secrets'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: Sandbox
    versionselect: Weekly  # Weekly in stead of Daily save lots of time a day because there are multiple new artifacts per day