name: $(Build.BuildId)

trigger: none

variables:
- group: 'Secrets'  # link to a variable group that has secret variables, like URL to license file.

pool: HOD-DOCKER

steps:
- checkout: self
  clean: true 
- task: ALOpsInfo@1

- task: ALOpsInfo@3
  inputs:
    showyaml: true
    showenvironmentvariables: true
    showtaskinputs: true
    showdockercontainers: true
    showdockerimages: true