name: 'HSM Code Signing with Azure Key Vault'

# This example demonstrates how to use ALOps for HSM-based code signing
# with Azure Key Vault, addressing the questions from GitHub issue #856

trigger:
  branches:
    include:
    - main
    - develop

pool: 'your-build-pool'

variables:
- group: 'HSM-CodeSigning-Variables' # Contains secure variables:
  # - AzureTenantId: Azure AD Tenant ID
  # - KeyVaultClientId: App Registration Client ID  
  # - KeyVaultClientSecret: App Registration Client Secret
  # - KeyVaultName: Name of your Azure Key Vault
  # - CertificateName: Certificate name in Key Vault

parameters:
- name: environment
  displayName: 'Target Environment'
  type: string
  default: 'Development'
  values:
  - 'Development'
  - 'Test'
  - 'Production'

stages:
- stage: 'BuildAndSign'
  displayName: 'Build and Sign Business Central Apps'
  
  jobs:
  - job: 'CompileAndSign'
    displayName: 'Compile and Sign Apps'
    
    steps:
    - checkout: self
      clean: true
      displayName: 'Checkout Source Code'

    # Compile the Business Central app
    - task: ALOpsAppCompiler@2
      displayName: 'Compile Business Central App'
      inputs:
        artifacttype: 'Sandbox'
        artifactcountry: 'w1'
        versionselect: 'Latest'
        appversiontemplate: '1.0.$(Build.BuildId).0'
        alsourcepath: '$(System.DefaultWorkingDirectory)/src'
        publishartifact: false # Don't publish yet, we'll sign first

    # Sign the compiled app using HSM with Azure Key Vault
    - task: ALOpsAppSign@1
      displayName: 'Sign App with Azure Key Vault HSM'
      inputs:
        # HSM Configuration
        signmethod: HSM                          # Use HSM signing (modern approach)
        hsmmethod: KEYVAULT                      # Use Azure Key Vault for HSM
        usedocker: false                         # HSM requires direct agent access
        
        # Artifact Configuration
        artifact_path: $(ALOPS_COMPILE_ARTIFACT) # Path from compiler step
        nav_artifact_app_filter: '*.app'         # Sign all .app files
        
        # Azure Key Vault Settings
        hsm_keyvault_name: '$(KeyVaultName)'     # e.g., 'contoso-codesigning-kv'
        hsm_keyvault_certificate_name: '$(CertificateName)' # e.g., 'codesigning-cert-2024'
        hsm_tenantid: '$(AzureTenantId)'         # Azure AD Tenant ID
        hsm_clientid: '$(KeyVaultClientId)'      # App Registration Client ID
        hsm_client_secret: '$(KeyVaultClientSecret)' # App Registration Secret
        
        # Signing Metadata (embedded in signature)
        # These are descriptive fields that don't need to match Azure resources
        hsm_description: 'Business Central App - ${{ parameters.environment }}' # Description of what's being signed
        hsm_description_url: 'https://www.yourcompany.com' # Your company URL
        hsm_digestalgorithm: 'sha256'           # Cryptographic hash algorithm
        
        # Timestamp Configuration
        timestamp_uri: 'http://timestamp.digicert.com' # Timestamp server for long-term validation
        
        # Output Configuration
        publish_artifact: true                   # Publish signed artifacts

    # Verify the signature was applied correctly
    - task: ALOpsAppSignVerify@1
      displayName: 'Verify Code Signature'
      inputs:
        usedocker: false
        artifact_path: $(ALOPS_COMPILE_ARTIFACT)
        nav_artifact_app_filter: '*.app'

    # Publish the signed artifacts for deployment
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Signed Apps'
      inputs:
        PathtoPublish: '$(ALOPS_COMPILE_ARTIFACT)'
        ArtifactName: 'SignedApps-${{ parameters.environment }}'
        publishLocation: 'Container'

    # Optional: Upload to AppSource or deploy to environments
    - task: ALOpsExtensionAPI@1
      displayName: 'Deploy to ${{ parameters.environment }} Environment'
      condition: and(succeeded(), ne('${{ parameters.environment }}', 'Production'))
      inputs:
        azure_tenant_id: '$(AzureTenantId)'
        azure_app_client_id: '$(BCClientId)'
        azure_app_client_secret: '$(BCClientSecret)'
        api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(AzureTenantId)/${{ parameters.environment }}/api'
        interaction: 'publish'
        artifact_path: $(ALOPS_COMPILE_ARTIFACT)
        artifact_filter: '*.app'

# Example variable group configuration:
# 
# Variable Group: HSM-CodeSigning-Variables
# Variables:
# - AzureTenantId: "12345678-1234-1234-1234-123456789012" (your Azure AD tenant)
# - KeyVaultName: "contoso-codesigning-kv" (your Key Vault name)
# - CertificateName: "codesigning-cert-2024" (certificate name in Key Vault)
# - KeyVaultClientId: "87654321-4321-4321-4321-210987654321" (App Registration ID)
# - KeyVaultClientSecret: "your-secret-value" (mark as secret!)
# - BCClientId: "your-bc-client-id" (for deployment, if different)
# - BCClientSecret: "your-bc-client-secret" (for deployment, mark as secret!)

# Prerequisites for build agents:
# 1. .NET 8.0 SDK installed
# 2. Visual C++ Redistributable 2013 installed  
# 3. navsip.dll registered (for Business Central app signing)
# 4. Network access to Azure Key Vault and timestamp servers
# 5. App Registration has proper Key Vault permissions:
#    - Certificate permissions: get, list
#    - Key permissions: get, list, sign
#    - Secret permissions: get, list

# Key Vault setup commands (run once):
# az keyvault create --name "contoso-codesigning-kv" --resource-group "rg-codesigning" --sku premium
# az ad app create --display-name "ALOps Code Signing"
# az ad sp create --id <app-id>
# az keyvault set-policy --name "contoso-codesigning-kv" --spn <client-id> --certificate-permissions get list --key-permissions get list sign
