#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps AppSource
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId 'dd485d1f-5be6-4ba3-a0e8-12c53a1ff81e'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['AzureTenantId'] = Read-GitHubInput -Name 'azure_tenant_id'
$P['AzureAppClientId'] = Read-GitHubInput -Name 'azure_app_client_id'
$P['SellerId'] = Read-GitHubInput -Name 'seller_id'
$P['OfferingNameFilter'] = Read-GitHubInput -Name 'offering_name_filter'
$P['AutopromoteCheckDelay'] = Read-GitHubInput -Name 'autopromote_check_delay'
$P['AutopromoteMaxTries'] = Read-GitHubInput -Name 'autopromote_max_tries'

$P['ApplyOfferingVersionFilter'] = Read-GitHubInput -Name 'apply_offering_version_filter' -AsBool
$P['SkipVersionChange'] = Read-GitHubInput -Name 'skip_version_change' -AsBool
$P['Autopromote'] = Read-GitHubInput -Name 'autopromote' -AsBool

$P['AzureAppClientSecret'] = Read-GitHubInput -Name 'azure_app_client_secret'
if ($P['AzureAppClientSecret']) { Protect-ALOpsSecret $P['AzureAppClientSecret'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAppSourceV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps AppSource completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
