#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps Docker Start
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId '0c42062e-04ee-4507-af30-009a5d8f1983'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['FixedTag'] = Read-GitHubInput -Name 'fixed_tag'
$P['DockerImage'] = Read-GitHubInput -Name 'docker_image'
$P['ContainerRestart'] = Read-GitHubInput -Name 'container_restart'
$P['MemoryGb'] = Read-GitHubInput -Name 'memory_gb'
$P['DockerParameters'] = Read-GitHubInput -Name 'docker_parameters'
$P['DockerAuthentication'] = Read-GitHubInput -Name 'docker_authentication'
$P['DockerUsername'] = Read-GitHubInput -Name 'docker_username'
$P['DockerRegistry'] = Read-GitHubInput -Name 'docker_registry'
$P['SqlServer'] = Read-GitHubInput -Name 'sql_server'
$P['SqlServerInstance'] = Read-GitHubInput -Name 'sql_server_instance'
$P['SqlDatabase'] = Read-GitHubInput -Name 'sql_database'
$P['SqlDatabaseUser'] = Read-GitHubInput -Name 'sql_database_user'
$P['SqlBackupFile'] = Read-GitHubInput -Name 'sql_backup_file'
$P['Licensefile'] = Read-GitHubInput -Name 'licensefile'
$P['EncryptionKey'] = Read-GitHubInput -Name 'encryption_key'
$P['Taskscheduler'] = Read-GitHubInput -Name 'taskscheduler'
$P['KeyvaultPfxfile'] = Read-GitHubInput -Name 'keyvault_pfxfile'
$P['KeyvaultClientid'] = Read-GitHubInput -Name 'keyvault_clientid'

$P['IgnoreNoContainerWarning'] = Read-GitHubInput -Name 'ignore_no_container_warning' -AsBool
$P['DockerPull'] = Read-GitHubInput -Name 'docker_pull' -AsBool
$P['AcceptImageEula'] = Read-GitHubInput -Name 'accept_image_eula' -AsBool
$P['AcceptImageOutdated'] = Read-GitHubInput -Name 'accept_image_outdated' -AsBool
$P['EnableSymbolLoading'] = Read-GitHubInput -Name 'enable_symbol_loading' -AsBool
$P['EnableApiServices'] = Read-GitHubInput -Name 'enable_api_services' -AsBool
$P['Multitenant'] = Read-GitHubInput -Name 'multitenant' -AsBool
$P['KeyvaultPublisherValidation'] = Read-GitHubInput -Name 'keyvault_publisher_validation' -AsBool

$P['DockerPassword'] = Read-GitHubInput -Name 'docker_password'
if ($P['DockerPassword']) { Protect-ALOpsSecret $P['DockerPassword'] }
$P['SqlDatabaseUserPassword'] = Read-GitHubInput -Name 'sql_database_user_password'
if ($P['SqlDatabaseUserPassword']) { Protect-ALOpsSecret $P['SqlDatabaseUserPassword'] }
$P['KeyvaultPfxpassword'] = Read-GitHubInput -Name 'keyvault_pfxpassword'
if ($P['KeyvaultPfxpassword']) { Protect-ALOpsSecret $P['KeyvaultPfxpassword'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsDockerStartV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps Docker Start completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
