#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps Admin Center API
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId '7e7fcf68-7a9b-40ba-9d8d-51090ca8ad77'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['AzureTenantId'] = Read-GitHubInput -Name 'azure_tenant_id'
$P['AzureAppClientId'] = Read-GitHubInput -Name 'azure_app_client_id'
$P['AzureAppClientCertificate'] = Read-GitHubInput -Name 'azure_app_client_certificate'
$P['Username'] = Read-GitHubInput -Name 'username'
$P['Checksecondsdelay'] = Read-GitHubInput -Name 'checksecondsdelay'
$P['Maxtries'] = Read-GitHubInput -Name 'maxtries'
$P['Interaction'] = Read-GitHubInput -Name 'interaction'
$P['Environment'] = Read-GitHubInput -Name 'environment'
$P['TargetEnvironment'] = Read-GitHubInput -Name 'target_environment'
$P['TargetEnvironmentType'] = Read-GitHubInput -Name 'target_environment_type'
$P['ApplicationInsightskey'] = Read-GitHubInput -Name 'application_insightskey'
$P['SecurityGroupId'] = Read-GitHubInput -Name 'security_group_id'
$P['AppId'] = Read-GitHubInput -Name 'app_id'

$P['WaitForOperation'] = Read-GitHubInput -Name 'wait_for_operation' -AsBool
$P['UseUpdateWindow'] = Read-GitHubInput -Name 'use_update_window' -AsBool
$P['AcceptIsvEula'] = Read-GitHubInput -Name 'accept_isv_eula' -AsBool
$P['ForceDependencies'] = Read-GitHubInput -Name 'force_dependencies' -AsBool
$P['ConfirmDeleteData'] = Read-GitHubInput -Name 'confirm_delete_data' -AsBool

$P['AzureAppClientSecret'] = Read-GitHubInput -Name 'azure_app_client_secret'
if ($P['AzureAppClientSecret']) { Protect-ALOpsSecret $P['AzureAppClientSecret'] }
$P['AzureAppClientCertificatePassword'] = Read-GitHubInput -Name 'azure_app_client_certificate_password'
if ($P['AzureAppClientCertificatePassword']) { Protect-ALOpsSecret $P['AzureAppClientCertificatePassword'] }
$P['Password'] = Read-GitHubInput -Name 'password'
if ($P['Password']) { Protect-ALOpsSecret $P['Password'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsAdminCenterAPIV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps Admin Center API completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
