#!/usr/bin/env pwsh
# =============================================================================
# GitHub Actions Wrapper Template
# =============================================================================
# AUTO-GENERATED by ManifestGenerator — DO NOT EDIT by hand.
# Task: ALOps Docker Create
#
# This wrapper does exactly three things:
#   1. Import the module and call Initialize-ALOpsTask
#   2. Read inputs from INPUT_* environment variables
#   3. Call the step function with those inputs
#
# NO BUSINESS LOGIC HERE.
#
# Initialize-ALOpsTask must be the first ALOps call: it registers the CI
# platform, resolves the task manifest from the sealed registry, validates
# the license, and opens the LicenseGate. Every other ALOps cmdlet and step
# function is gated on that call — removing it from this wrapper turns the
# very next ALOps cmdlet into a terminating error.
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ── 1. Import Module & Initialize Task ──────────────────────────────────────

Install-Module -Name ALOpsV3.Module -AllowPrerelease -Scope CurrentUser -AllowClobber -Force
Import-Module -Name ALOpsV3.Module -Force -DisableNameChecking

Initialize-ALOpsTask -TaskId 'f4c04016-bb3f-4614-b978-ce92409ce78a'

Write-ALOpsInfo "ALOpsV3.Module version: $((Get-Module -Name ALOpsV3.Module).Version)"

# ── Input Reader Helper ──────────────────────────────────────────────────

function Read-GitHubInput {
    param(
        [string] $Name,
        [switch] $AsBool
    )
    $envName = 'INPUT_' + $Name.ToUpper().Replace('-','_').Replace(' ','_')
    $val = [System.Environment]::GetEnvironmentVariable($envName)

    if ($AsBool) { return ($val -match '^(true|yes|1)$') }
    return $val
}

# ── 2. Read Inputs ────────────────────────────────────────────────────────

$P = @{}

$P['ArtifactSpecification'] = Read-GitHubInput -Name 'artifact_specification'
$P['ArtifactVersion'] = Read-GitHubInput -Name 'artifact_version'
$P['ArtifactType'] = Read-GitHubInput -Name 'artifact_type'
$P['ArtifactCountry'] = Read-GitHubInput -Name 'artifact_country'
$P['VersionSelect'] = Read-GitHubInput -Name 'version_select'
$P['ArtifactHint'] = Read-GitHubInput -Name 'artifact_hint'
$P['AlternativeArtifactUrl'] = Read-GitHubInput -Name 'alternative_artifact_url'
$P['StorageAccount'] = Read-GitHubInput -Name 'storage_account'
$P['ImagePrefix'] = Read-GitHubInput -Name 'image_prefix'
$P['ImageNameTemplate'] = Read-GitHubInput -Name 'image_name_template'
$P['UseGenericImage'] = Read-GitHubInput -Name 'use_generic_image'
$P['Memory'] = Read-GitHubInput -Name 'memory'
$P['MyScripts'] = Read-GitHubInput -Name 'my_scripts'
$P['DockerRegistry'] = Read-GitHubInput -Name 'docker_registry'
$P['DockerUsername'] = Read-GitHubInput -Name 'docker_username'
$P['LicenseFile'] = Read-GitHubInput -Name 'license_file'

$P['ForceCreateImage'] = Read-GitHubInput -Name 'force_create_image' -AsBool
$P['IncludeTestToolkit'] = Read-GitHubInput -Name 'include_test_toolkit' -AsBool
$P['IncludeTestLibrariesOnly'] = Read-GitHubInput -Name 'include_test_libraries_only' -AsBool
$P['IncludeTestFrameworkOnly'] = Read-GitHubInput -Name 'include_test_framework_only' -AsBool
$P['IncludePerformanceToolkit'] = Read-GitHubInput -Name 'include_performance_toolkit' -AsBool
$P['AcceptInsiderEula'] = Read-GitHubInput -Name 'accept_insider_eula' -AsBool
$P['Multitenant'] = Read-GitHubInput -Name 'multitenant' -AsBool

$P['SasToken'] = Read-GitHubInput -Name 'sas_token'
if ($P['SasToken']) { Protect-ALOpsSecret $P['SasToken'] }
$P['DockerPassword'] = Read-GitHubInput -Name 'docker_password'
if ($P['DockerPassword']) { Protect-ALOpsSecret $P['DockerPassword'] }

# ── Log Parameters ───────────────────────────────────────────────────────
# Values can be customer-controlled (e.g. an inline script). Azure DevOps
# (##[…] / ##vso[…]) and GitHub (::…) parse such tokens at the START of a log
# line as commands, so echoing a multi-line value verbatim lets it inject
# phantom log issues. Print continuation lines behind a non-whitespace guard
# so no embedded token can begin a line.

Write-ALOpsGroup "Task Parameters" {
    $P.GetEnumerator() | Sort-Object Name | ForEach-Object {
        $valueLines = ([string]$_.Value) -split "`r?`n"
        Write-ALOpsInfo ("  * {0,-45} = {1}" -f $_.Name, $valueLines[0])
        $valueLines | Select-Object -Skip 1 | ForEach-Object {
            Write-ALOpsInfo "      | $_"
        }
    }
}

# ── 3. Call Step Function ─────────────────────────────────────────────────

try {
    Run-ALOpsDockerCreateV3Step @P
    Set-ALOpsResult -Result "Succeeded" -Message "ALOps Docker Create completed successfully."
    exit 0
}
catch {
    Write-ALOpsError -Message $_.Exception.Message -ScriptStackTrace $_.ScriptStackTrace
    Write-Host $_.ScriptStackTrace
    Set-ALOpsResult -Result "Failed" -Message $_.Exception.Message
    exit 1
}
