name: GitHub Actions Demo Linux
run-name: ${{ github.actor }} is testing out GitHub Actions LINUX
on:
  workflow_dispatch:
env:
  alops-licenseid: "4ca728fd-d941-4818-a844-5fa3296b604f"
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: ALOps Info
        uses: HodorNV/ALOps/Actions/alops-info@master

      - name: ALOps OpenAPI
        uses: HodorNV/ALOps/Actions/alops-openapi@master
        with:
          api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/20101739-aeb8-49c3-a6c9-0fc2d55dcd30/QA/api'
          authentication: 'oauth'
          azure_tenant_id: '20101739-aeb8-49c3-a6c9-0fc2d55dcd30'
          azure_app_client_id: '249da451-27d1-4ff7-920c-b14f2b397436'
          azure_app_client_secret: '${{ secrets.BC_SAAS_SECRET }}'
          api_exclude_routes: |
            beta
            v1.0
          inspect_paths: true
          api_servers: 'server.com'
          export_edmx: true
          export_json: true
          exclude_company_paths: true
          
      - name: ALOps App License Check
        uses: HodorNV/ALOps/Actions/alops-applicensecheck@master
        with:
          licensefile: '.resources/6676359 BC25 DEV NL 20260211.bclicense'

      - name: AdminCenterAPI
        uses: ./.github/actions/alops-admincenterapi
        with:
          azure_tenant_id: '20101739-aeb8-49c3-a6c9-0fc2d55dcd30'
          azure_app_client_id: '249da451-27d1-4ff7-920c-b14f2b397436'
          azure_app_client_secret: '${{ secrets.BC_SAAS_SECRET }}'
          interaction: environment_list

      - name: ALOps Compile
        id: alops-compile
        uses: ./.github/actions/alops-appcompiler
        with:
          compilation_mode: 'Serial'
          preprocessorsymbols: 'BC270'

      - name: ALOps App Sign
        uses: ./.github/actions/alops-appsign
        continue-on-error: true
        with:       
          signmethod: 'PFX'
          pfx_path: '${{ secrets.SIGN_PFX_CERT }}'
          pfx_password: '${{ secrets.SIGN_PFX_PWD }}'
          timestamp_uri: 'http://timestamp.digicert.com'
          batchsigncompiledapps: true

      - name: ALOps App Symbol
        uses: ./.github/actions/alops-appsymbol
        with:
          use_alops_compiler_apps: true      
          verify_symbol: true
          artifact_name: 'ALOpsSymbol'

      - name: ALOps NuGet Download
        uses: ./.github/actions/alops-nugetdownload
        with:
          nuget_spec_file: '.resources/nuget.json'
          artifact_folder_name: 'Nuget'

      - name: ALOps Extension API
        uses: ./.github/actions/alops-extensionapi
        with:
          interaction: 'get'
          api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/20101739-aeb8-49c3-a6c9-0fc2d55dcd30/QA/api'
          azure_tenant_id: '20101739-aeb8-49c3-a6c9-0fc2d55dcd30'
          azure_app_client_id: '249da451-27d1-4ff7-920c-b14f2b397436'
          azure_app_client_secret: '${{ secrets.BC_SAAS_SECRET }}'




      # - name: Nuget Download
      #   uses: ./.github/actions/alops-nugetdownload
      #   with:
      #     nuget_spec_file: 'nuget.json'
      #     artifact_folder_name: 'Nuget'
      # - name: Nuget Resolved Download
      #   uses: ./.github/actions/alops-nugetdownload
      #   with:
      #     nuget_spec_file: 'nuget.resolved.json'
      #     artifact_folder_name: 'NugetResolved'

      # - name: Upload ALOps Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ALOpsArtifact1
      #     path: ${{ steps.alops-compile.outputs.artifact_path }}  
      # - name: Upload ALOps Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ALOpsArtifact2
      #     path: ${{ env.ALOPS_COMPILE_ARTIFACT }}
